# Data Configuration
data:
  dataset_id: "harshitstark/bank-churn-train"
  filename: "train.csv"
  test_size: 0.2
  random_state: 42

# MLflow Configuration
mlflow:
  experiment_name: "Bank Churn Prediction"
  tracking_uri: "http://127.0.0.1:5000"
  server_host: "0.0.0.0"
  server_port: 5000

# Model Configuration
models:
  logistic_regression:
    max_iter: 1000
    random_state: 42
    
  random_forest:
    n_estimators: 100
    max_depth: 10
    random_state: 42
    n_jobs: -1

# Preprocessing
preprocessing:
  columns_to_drop:
    - id
    - CustomerId
    - Surname
  encoding:
    method: "one_hot"
    drop_first: true
